import DashboardNavigation from "@/components/DashboardNavigation/DashboardNavigation";

export const metadata = {
  title: 'EasyChat - Dashboard',
  description: 'Generated by Next.js',
}

export default function RootLayout({children}: { children: React.ReactNode }) {
  return (
      <main className="min-h-screen grid grid-rows-[1fr,4rem] grid-cols-1">
        {children}
        <DashboardNavigation/>
      </main>
  )
}
